### PR TITLE
Bump package version to 1.8.0

### PR DESCRIPTION
**Pull request by abdelnn**
*Description of changes:*
Bump package version to `1.8.0` to release support for new intrinsic functions and map state.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by vishalsatam-aws** [comment]
I think we need to upgrade the minor version in this case since we added a whole new feature and a change in spec for ASL, don't we?

**Review by evscott — DISMISSED** [review]

**Comment by shivlaks** [comment]
> I think we need to upgrade the minor version in this case since we added a whole new feature and a change in spec for ASL, don't we?

I don't think we've been consistent with version bumps... but i tend to agree. Added functionality that is backwards compatible should be represented by incrementing the minor version. bumping the `z` is really for backwards compatible patches...

**Comment by vishalsatam-aws** [comment]
>are there any functional concerns you have between the two @vishalsatam-aws

No functional concerns for this library because I think its only being used for AWS Toolkit which should technically always fetch and support the latest version of this package.

But since this is a public repo, I don't know if customers are using this for other cases. If they were and if they wanted to keep the old validation without Distributed Map (for some reason), we won't be able to provide a patch for such cases.

I still don't see the harm in bumping the minor version to 1.8.0 .. It's just a one line change, isn't it? Or is there something else I'm missing?

**Comment by evscott** [comment]
https://semver.org/

> MINOR version when you add functionality in a backwards compatible manner

A minor version bump in this case makes sense.

**Comment by abdelnn** [comment]
Makes sense, will update

**Comment by shivlaks** [comment]
> I still don't think there is any downside to bumping the minor version to 1.8.0 now .. It's just a one line change, isn't it? Or is there something else I'm missing @shivlaks ?

a minor version bump makes sense to me. i don't think the code changes required is as important as understanding why we are doing it and was intentionally open to both. thanks for raising it @vishalsatam-aws

**Review by shivlaks — DISMISSED** [review]
please update the PR description before merging

**Review by vishalsatam-aws — APPROVED** [review]

**Review by shivlaks — APPROVED** [review]

**Review by evscott — APPROVED** [review]

**Review by jormello — APPROVED** [review]

**Review by vishalsatam-aws — APPROVED** [review]

**Pull request merged**
